spring:
  application:
    name: Operation_module

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: ${MODULE_GROUP_ID}

operation:
  timeout: 10
  ttl: 3600